### ISSUE TITLE
сложно

### ISSUE THREAD

**Issue by arefimenko** [crazy78cyxapuk/Cleaning_PC#1]
ничего непонятно, можно для тупых объяснить?

**Comment by crazy78cyxapuk** [comment]
приветствую. конечно могу, что именно Вас интересует?

> ничего непонятно, можно для тупых объяснить?

**Comment by arefimenko** [comment]
![image](https://user-images.githubusercontent.com/54911543/114009801-2768c680-986c-11eb-9eb0-31a1c18a66c0.png)
в файле `UserSettings` указаны такие параметры, которые я не устанавливал. Зачем вы меняете мои данные на свои?

**Comment by crazy78cyxapuk** [comment]
с такими вопросами лучше писать сюда: [https://forum.unity.com/](ссылка)
Ваши данные изменяет непосредственно сам движок, возможно это даже баг, который мешает не только Вам.

**Comment by arefimenko** [comment]
Понял принял, спасибо. Будем решать вопросики с ними
